include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # 代码风格
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true

    # 命名规范
    constant_identifier_names: true
    file_names: true
    package_names: true

    # 类型安全
    always_specify_types: false
    avoid_dynamic_calls: true
    avoid_returning_null: true

    # 性能
    avoid_slow_async_io: true
    avoid_unused_constructor_parameters: true
